/**
 * Generates tokens.css from tokens.json.
 * Outputs:
 *   - dist/tokens.css  (full CSS variable sheet, light + dark)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const tokens = JSON.parse(readFileSync(join(root, 'src/tokens.json'), 'utf8'));

const p = tokens.primitive;

function lines(...parts) {
  return parts.flat().join('\n');
}

const css = lines(
  `/* Auto-generated by build-css.mjs — do not edit directly */`,
  `/* Edit packages/tokens/src/tokens.json instead */`,
  ``,
  `/* ─── Primitive tokens ──────────────────────────────── */`,
  `:root {`,
  // colors
  ...Object.entries(p.color).flatMap(([name, shades]) =>
    Object.entries(shades).map(([shade, val]) => `  --color-${name}-${shade}: ${val};`)
  ),
  // spacing
  ...Object.entries(p.spacing).map(([k, v]) => `  --spacing-${k}: ${v};`),
  // size (control heights, checkbox dimensions — φ/Fibonacci-derived)
  ...Object.entries(p.size).map(([k, v]) => `  --size-${k}: ${v};`),
  // radius
  ...Object.entries(p.radius).map(([k, v]) => `  --radius-${k}: ${v};`),
  // border width
  ...Object.entries(p.borderWidth).map(([k, v]) => `  --border-width-${k}: ${v};`),
  // font family
  ...Object.entries(p.font.family).map(([k, v]) => `  --font-family-${k}: ${v};`),
  // font size
  ...Object.entries(p.font.size).map(([k, v]) => `  --font-size-${k}: ${v};`),
  // font weight
  ...Object.entries(p.font.weight).map(([k, v]) => `  --font-weight-${k}: ${v};`),
  // line height
  ...Object.entries(p.font.lineHeight).map(([k, v]) => `  --line-height-${k}: ${v};`),
  // letter spacing
  ...Object.entries(p.font.letterSpacing).map(([k, v]) => `  --letter-spacing-${k}: ${v};`),
  // shadows
  ...Object.entries(p.shadow).map(([k, v]) => `  --shadow-${k}: ${v};`),
  // transitions
  ...Object.entries(p.transition.duration).map(([k, v]) => `  --transition-duration-${k}: ${v};`),
  ...Object.entries(p.transition.easing).map(([k, v]) => `  --transition-easing-${k}: ${v};`),
  // shorthand transition helpers
  `  --transition-fast:   ${p.transition.duration.fast} ${p.transition.easing.default};`,
  `  --transition-normal: ${p.transition.duration.normal} ${p.transition.easing.default};`,
  `  --transition-slow:   ${p.transition.duration.slow} ${p.transition.easing.default};`,
  // opacity (successive powers of 1/φ ≈ 0.618)
  ...Object.entries(p.opacity).map(([k, v]) => `  --opacity-${k}: ${v};`),
  // z-index
  ...Object.entries(p.zIndex).map(([k, v]) => `  --z-index-${k}: ${v};`),
  // breakpoints (for JS access; use raw values in @media queries)
  ...Object.entries(p.breakpoint).map(([k, v]) => `  --breakpoint-${k}: ${v};`),
  ``,
  `  /* ── Composite tokens (derived from primitives) ──── */`,
  `  --color-overlay: color-mix(in srgb, var(--color-foreground) 38.2%, transparent);`,
  `  --focus-ring-color: color-mix(in srgb, var(--color-focus-ring) 20%, transparent);`,
  `  --focus-ring: 0 0 0 3px var(--focus-ring-color);`,
  `  --focus-ring-inset: inset 0 0 0 3px var(--focus-ring-color);`,
  `  --focus-ring-error: 0 0 0 3px color-mix(in srgb, var(--color-destructive) 20%, transparent);`,
  `}`,
  ``,
  `/* ─── Semantic tokens — light mode ─────────────────── */`,
  `:root, [data-theme="light"] {`,
  `  --color-background:           ${p.color.stone[50]};`,
  `  --color-background-subtle:    ${p.color.stone[100]};`,
  `  --color-background-surface:   ${p.color.stone[0]};`,
  `  --color-foreground:           ${p.color.stone[950]};`,
  `  --color-foreground-subtle:    ${p.color.stone[500]};`,
  `  --color-foreground-muted:     ${p.color.stone[400]};`,
  `  --color-foreground-secondary: ${p.color.stone[600]};`,
  `  --color-border:               ${p.color.stone[200]};`,
  `  --color-border-strong:        ${p.color.stone[300]};`,
  `  --color-primary:              ${p.color.stone[800]};`,
  `  --color-primary-hover:        ${p.color.stone[900]};`,
  `  --color-primary-foreground:   ${p.color.stone[0]};`,
  `  --color-secondary:            ${p.color.stone[200]};`,
  `  --color-secondary-hover:      ${p.color.stone[300]};`,
  `  --color-secondary-foreground: ${p.color.stone[900]};`,
  `  --color-destructive:          ${p.color.brick[600]};`,
  `  --color-destructive-hover:    ${p.color.brick[700]};`,
  `  --color-destructive-foreground: ${p.color.stone[0]};`,
  `  --color-success:              ${p.color.sage[600]};`,
  `  --color-warning:              ${p.color.amber[600]};`,
  `  --color-info:                 ${p.color.slate[600]};`,
  `  --color-info-subtle:          ${p.color.slate[50]};`,
  `  --color-info-foreground:      ${p.color.slate[700]};`,
  `  --color-focus-ring:           ${p.color.stone[700]};`,
  `  --color-primary-active:      ${p.color.stone[950]};`,
  `  --color-secondary-active:    ${p.color.stone[300]};`,
  `  --color-destructive-active:  ${p.color.brick[700]};`,
  `  --color-success-subtle:     ${p.color.sage[50]};`,
  `  --color-success-foreground: ${p.color.sage[700]};`,
  `  --color-warning-subtle:     ${p.color.amber[50]};`,
  `  --color-warning-foreground: ${p.color.amber[700]};`,
  `  --color-destructive-subtle: ${p.color.brick[50]};`,
  `}`,
  ``,
  `/* ─── Semantic tokens — dark mode ──────────────────── */`,
  `.dark, [data-theme="dark"] {`,
  `  --color-background:           ${p.color.stone[950]};`,
  `  --color-background-subtle:    ${p.color.stone[900]};`,
  `  --color-background-surface:   ${p.color.stone[900]};`,
  `  --color-foreground:           ${p.color.stone[50]};`,
  `  --color-foreground-subtle:    ${p.color.stone[400]};`,
  `  --color-foreground-muted:     ${p.color.stone[500]};`,
  `  --color-foreground-secondary: ${p.color.stone[300]};`,
  `  --color-border:               ${p.color.stone[800]};`,
  `  --color-border-strong:        ${p.color.stone[700]};`,
  `  --color-primary:              ${p.color.stone[200]};`,
  `  --color-primary-hover:        ${p.color.stone[100]};`,
  `  --color-primary-foreground:   ${p.color.stone[950]};`,
  `  --color-secondary:            ${p.color.stone[800]};`,
  `  --color-secondary-hover:      ${p.color.stone[700]};`,
  `  --color-secondary-foreground: ${p.color.stone[50]};`,
  `  --color-destructive:          ${p.color.brick[500]};`,
  `  --color-destructive-hover:    ${p.color.brick[400]};`,
  `  --color-destructive-foreground: ${p.color.stone[950]};`,
  `  --color-success:              ${p.color.sage[500]};`,
  `  --color-warning:              ${p.color.amber[500]};`,
  `  --color-info:                 ${p.color.slate[400]};`,
  `  --color-info-subtle:          color-mix(in srgb, var(--color-info) 12%, var(--color-background-subtle));`,
  `  --color-info-foreground:      ${p.color.slate[300]};`,
  `  --color-focus-ring:           ${p.color.stone[400]};`,
  `  --color-primary-active:      ${p.color.stone[50]};`,
  `  --color-secondary-active:    ${p.color.stone[700]};`,
  `  --color-destructive-active:  ${p.color.brick[400]};`,
  `  --color-success-subtle:     color-mix(in srgb, var(--color-success) 12%, var(--color-background-subtle));`,
  `  --color-success-foreground: ${p.color.sage[400]};`,
  `  --color-warning-subtle:     color-mix(in srgb, var(--color-warning) 12%, var(--color-background-subtle));`,
  `  --color-warning-foreground: ${p.color.amber[400]};`,
  `  --color-destructive-subtle: color-mix(in srgb, var(--color-destructive) 12%, var(--color-background-subtle));`,
  `}`,
);

const globals = lines(
  ``,
  `/* ─── Scrollbar hiding utility ──────────────────────── */`,
  `.ds-scroll-hidden { scrollbar-width: none; }`,
  `.ds-scroll-hidden::-webkit-scrollbar { display: none; }`,
  ``,
  `/* ─── Form element font inheritance ────────────────── */`,
  `/* Browsers don't inherit font on form controls — fix globally */`,
  `button, input, select, textarea {`,
  `  font-family: inherit;`,
  `}`,
  ``,
  `/* ─── Global focus-visible ──────────────────────────── */`,
  `/* Safety-net focus ring for any element not styled by a component */`,
  `*:focus-visible {`,
  `  outline: 2px solid var(--color-focus-ring);`,
  `  outline-offset: 2px;`,
  `}`,
  ``,
  `/* ─── Reduced motion ────────────────────────────────── */`,
  `/* Respect OS-level "reduce motion" accessibility setting */`,
  `@media (prefers-reduced-motion: reduce) {`,
  `  *, *::before, *::after {`,
  `    animation-duration: 0.01ms !important;`,
  `    animation-iteration-count: 1 !important;`,
  `    transition-duration: 0.01ms !important;`,
  `    scroll-behavior: auto !important;`,
  `  }`,
  `}`,
);

mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist/tokens.css'), css + globals + '\n');
console.log('✓ dist/tokens.css written');
