/**
 * Generates tokens.css from tokens.json.
 * Outputs:
 *   - dist/tokens.css  (full CSS variable sheet, light + dark)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const tokens = JSON.parse(readFileSync(join(root, 'src/tokens.json'), 'utf8'));

const p = tokens.primitive;

function lines(...parts) {
  return parts.flat().join('\n');
}

/**
 * Resolve a semantic $value. `{primitive.color.stone.500}` references are
 * looked up in tokens.json; anything else (e.g. color-mix() expressions)
 * passes through verbatim. An unresolvable reference FAILS the build —
 * CSS custom properties fail silently at runtime, so catch it here.
 */
function resolveValue(name, raw) {
  const ref = raw.match(/^\{(.+)\}$/);
  if (!ref) return raw;
  const value = ref[1].split('.').reduce((node, key) => node?.[key], tokens);
  if (typeof value !== 'string') {
    throw new Error(`Token "${name}" references "${raw}" which does not exist in tokens.json`);
  }
  return value;
}

/**
 * Guards the build adds on top of resolveValue():
 *  - Light and dark must define the same semantic names in the same order.
 *    A token defined in one mode only would silently keep the other mode's
 *    value inside a nested theme region.
 *  - var(--color-*) inside pass-through values (the color-mix() tokens) must
 *    name a primitive shade or a semantic token that exists — resolveValue()
 *    only checks {primitive.*} references.
 */
{
  const light = Object.keys(tokens.semantic.color.light);
  const dark = Object.keys(tokens.semantic.color.dark);
  if (light.join() !== dark.join()) {
    const only = (a, b) => a.filter((k) => !b.includes(k));
    throw new Error(
      `Semantic colour modes differ — light only: [${only(light, dark)}], dark only: [${only(dark, light)}]` +
        (only(light, dark).length || only(dark, light).length ? '' : ' (same names, different order)')
    );
  }
  for (const mode of ['light', 'dark']) {
    for (const [name, { $value }] of Object.entries(tokens.semantic.color[mode])) {
      for (const [, ref] of $value.matchAll(/var\(--color-([a-z0-9-]+)\)/g)) {
        const shade = ref.match(/^([a-z]+)-(\d+)$/);
        const ok = shade ? p.color[shade[1]]?.[shade[2]] !== undefined : ref in tokens.semantic.color[mode];
        if (!ok) throw new Error(`Token "${name}" (${mode}) uses var(--color-${ref}), which is not defined`);
      }
    }
  }
}

function semanticBlock(mode) {
  return Object.entries(tokens.semantic.color[mode]).map(
    ([name, { $value }]) => `  --color-${name}: ${resolveValue(name, $value)};`
  );
}

/**
 * Composite tokens — built from semantic colors, so they are emitted inside
 * EACH mode block rather than once on :root. A custom property's var()
 * references resolve where it is declared: declared only on :root, a
 * nested `.dark` region (a docs preview, a dark promo band) would inherit
 * the light-mode ring and overlay. Re-declaring per mode re-resolves them.
 *
 * Focus ring: a solid 2px ring in --color-focus-ring, separated from the
 * control by a 2px gap in the page background. The old 3px ring at 20%
 * alpha measured 1.4:1 against the page — invisible to many keyboard users
 * (WCAG 1.4.11 / 2.4.13 need 3:1). The solid ring is 8.7:1 light, 7.1:1 dark.
 *
 * Overlay: scrim for Modal/Drawer backdrops. Always darkens (stone-950) —
 * the old foreground-based mix turned light in dark mode and *lightened*
 * the page behind a dialog. Denser in dark mode (61.8% vs 38.2%, φ pair)
 * because a dark page needs more scrim to read as dimmed.
 */
function compositeBlock(mode) {
  const ring = 'var(--border-width-lg)';
  const ringOuter = `calc(${ring} * 2)`;
  return [
    `  /* composites — see compositeBlock() in build-css.mjs */`,
    `  --color-overlay: color-mix(in srgb, var(--color-stone-950) ${mode === 'dark' ? '61.8%' : '38.2%'}, transparent);`,
    `  --focus-ring-color: var(--color-focus-ring);`,
    `  --focus-ring: 0 0 0 ${ring} var(--color-background), 0 0 0 ${ringOuter} var(--color-focus-ring);`,
    `  --focus-ring-inset: inset 0 0 0 ${ring} var(--color-focus-ring);`,
    `  --focus-ring-error: 0 0 0 ${ring} var(--color-background), 0 0 0 ${ringOuter} var(--color-destructive);`,
  ];
}

const css = lines(
  `/* Auto-generated by build-css.mjs — do not edit directly */`,
  `/* Edit packages/tokens/src/tokens.json instead */`,
  ``,
  `/* ─── Primitive tokens ──────────────────────────────── */`,
  `:root {`,
  // colors
  ...Object.entries(p.color).flatMap(([name, shades]) =>
    Object.entries(shades).map(([shade, val]) => `  --color-${name}-${shade}: ${val};`)
  ),
  // spacing — includes fluid steps (--spacing-fluid-*): clamp() between adjacent
  // phi-scale values (16→26, 26→42, 42→68, 68→110px), interpolated linearly
  // across 375px→1200px viewports, same technique as the fluid type scale.
  ...Object.entries(p.spacing).map(([k, v]) => `  --spacing-${k}: ${v};`),
  // aspect ratios — φ-derived (golden = φ:1) plus practical media ratios
  ...Object.entries(p.aspect).map(([k, v]) => `  --aspect-${k}: ${v};`),
  // reading measure — 65ch optimal line length for body text
  ...Object.entries(p.measure).map(([k, v]) => `  --measure-${k}: ${v};`),
  // interaction scale — pressed-state transform shared by all pressable components
  ...Object.entries(p.scale).map(([k, v]) => `  --scale-${k}: ${v};`),
  // safe area — device notch/home-indicator insets, 0px fallback on desktop
  ...Object.entries(p.safeArea).map(([k, v]) => `  --safe-area-${k}: ${v};`),
  // size (control heights, checkbox dimensions — φ/Fibonacci-derived)
  ...Object.entries(p.size).map(([k, v]) => `  --size-${k}: ${v};`),
  // radius
  ...Object.entries(p.radius).map(([k, v]) => `  --radius-${k}: ${v};`),
  // border width
  ...Object.entries(p.borderWidth).map(([k, v]) => `  --border-width-${k}: ${v};`),
  // font family
  ...Object.entries(p.font.family).map(([k, v]) => `  --font-family-${k}: ${v};`),
  // font size
  ...Object.entries(p.font.size).map(([k, v]) => `  --font-size-${k}: ${v};`),
  // font weight
  ...Object.entries(p.font.weight).map(([k, v]) => `  --font-weight-${k}: ${v};`),
  // line height
  ...Object.entries(p.font.lineHeight).map(([k, v]) => `  --line-height-${k}: ${v};`),
  // letter spacing
  ...Object.entries(p.font.letterSpacing).map(([k, v]) => `  --letter-spacing-${k}: ${v};`),
  // shadows
  ...Object.entries(p.shadow).map(([k, v]) => `  --shadow-${k}: ${v};`),
  // transitions
  ...Object.entries(p.transition.duration).map(([k, v]) => `  --transition-duration-${k}: ${v};`),
  ...Object.entries(p.transition.easing).map(([k, v]) => `  --transition-easing-${k}: ${v};`),
  // shorthand transition helpers
  `  --transition-fast:   ${p.transition.duration.fast} ${p.transition.easing.default};`,
  `  --transition-normal: ${p.transition.duration.normal} ${p.transition.easing.default};`,
  `  --transition-slow:   ${p.transition.duration.slow} ${p.transition.easing.default};`,
  // motion — choreography primitives. Stagger continues the ×φ duration
  // series downward (100/φ = 62, 100/φ² = 38); distance reuses the
  // phi spacing steps so reveal travel sits on the same scale as layout.
  ...Object.entries(p.motion.stagger).map(([k, v]) => `  --motion-stagger-${k}: ${v};`),
  ...Object.entries(p.motion.distance).map(([k, v]) => `  --motion-distance-${k}: ${v};`),
  // opacity (successive powers of 1/φ ≈ 0.618)
  ...Object.entries(p.opacity).map(([k, v]) => `  --opacity-${k}: ${v};`),
  // z-index
  ...Object.entries(p.zIndex).map(([k, v]) => `  --z-index-${k}: ${v};`),
  // breakpoints (for JS access; use raw values in @media queries)
  ...Object.entries(p.breakpoint).map(([k, v]) => `  --breakpoint-${k}: ${v};`),
  ``,
  `  /* ── Semantic elevation (references, not copies) ─── */`,
  `  /* Emitted as var(--shadow-*) so a shadow-scale change flows through */`,
  ...Object.entries(tokens.semantic.elevation).map(
    ([k, { $value }]) => `  --elevation-${k}: ${$value};`
  ),
  `}`,
  ``,
  `/* ─── Semantic tokens — light mode ─────────────────── */`,
  `:root, [data-theme="light"] {`,
  `  color-scheme: light;`,
  semanticBlock('light'),
  compositeBlock('light'),
  `}`,
  ``,
  `/* ─── Semantic tokens — dark mode ──────────────────── */`,
  `.dark, [data-theme="dark"] {`,
  `  color-scheme: dark;`,
  semanticBlock('dark'),
  compositeBlock('dark'),
  `}`,
);

/**
 * Adaptive modes — both are token swaps only; no component needs to know.
 *
 * Print: paper is white. A page printed from dark mode would otherwise
 * come out as light text on white (backgrounds are dropped by default),
 * so every theme prints with the light semantic tokens.
 *
 * prefers-contrast: more (macOS "Increase contrast", Windows contrast
 * themes without forced colors): decorative borders take the 3:1 control
 * edge, and the two faintest text roles step up — one rung in light, two
 * in dark (so dark subtle lands on stone-300, the same as secondary).
 * border-strong moves too (to stone-500: 3.9:1 light, 4.7:1 dark) — left
 * alone it sat BELOW the raised --color-border, so hover borders
 * (CollectionFilters pill, ColorPicker ring) got fainter on hover.
 *
 * Order matters: print comes AFTER contrast. Printing with "Increase
 * contrast" on used to apply the dark contrast overrides (stone-300 text)
 * on top of print's light tokens — light grey on white paper. Print then
 * re-applies the light contrast overrides itself.
 */
const moreContrast = {
  light: [
    `--color-border: var(--color-border-control);`,
    `--color-border-strong: var(--color-stone-500);`,
    `--color-foreground-subtle: var(--color-stone-600);`,
    `--color-foreground-muted: var(--color-stone-500);`,
  ],
  dark: [
    `--color-border: var(--color-border-control);`,
    `--color-border-strong: var(--color-stone-500);`,
    `--color-foreground-subtle: var(--color-stone-300);`,
    `--color-foreground-muted: var(--color-stone-400);`,
  ],
};
const indent = (n, arr) => arr.map((l) => ' '.repeat(n) + l);

const adaptive = lines(
  ``,
  `/* ─── More contrast (OS setting) ──────────────────── */`,
  `@media (prefers-contrast: more) {`,
  `  :root, [data-theme="light"] {`,
  indent(4, moreContrast.light),
  `  }`,
  `  .dark, [data-theme="dark"] {`,
  indent(4, moreContrast.dark),
  `  }`,
  `}`,
  ``,
  `/* ─── Print: always the light theme ────────────────── */`,
  `@media print {`,
  `  :root, .dark, [data-theme="dark"] {`,
  `    color-scheme: light;`,
  semanticBlock('light').map((l) => '  ' + l),
  compositeBlock('light').map((l) => '  ' + l),
  `  }`,
  `}`,
  `@media print and (prefers-contrast: more) {`,
  `  :root, .dark, [data-theme="dark"] {`,
  indent(4, moreContrast.light),
  `  }`,
  `}`,
);

const globals = lines(
  ``,
  `/* ─── Scrollbars ────────────────────────────────────── */`,
  `/* Thin, token-colored thumb on an invisible track — recedes`,
  `   into the page instead of announcing itself, and swaps with`,
  `   the theme automatically. Standard properties only: they drive`,
  `   Chromium and Firefox, where the overlay scrollbar stays`,
  `   auto-hiding AND takes the token color. Safari ignores these`,
  `   props and keeps its NATIVE auto-hiding overlay scrollbar`,
  `   (uncolored) — a deliberate choice: styling ::-webkit-scrollbar`,
  `   is the only way to color it in Safari, but doing so forces an`,
  `   always-visible classic bar, which we don't want. Auto-hide`,
  `   wins over color there. See 06-decisions-log.md. */`,
  `* {`,
  `  scrollbar-width: thin;`,
  `  scrollbar-color: var(--color-border-strong) transparent;`,
  `}`,
  ``,
  `/* ─── Scrollbar hiding utility ──────────────────────── */`,
  `.ds-scroll-hidden { scrollbar-width: none; }`,
  `.ds-scroll-hidden::-webkit-scrollbar { display: none; }`,
  ``,
  `/* ─── Mobile Safari defaults ────────────────────────── */`,
  `/* iOS enlarges text when a phone rotates to landscape; the type scale is`,
  `   already fluid, so keep sizes as authored. The grey tap flash is`,
  `   replaced by each component's own pressed state (--scale-press etc.). */`,
  `html {`,
  `  -webkit-text-size-adjust: 100%;`,
  `  text-size-adjust: 100%;`,
  `  -webkit-tap-highlight-color: transparent;`,
  `}`,
  ``,
  `/* ─── Form element font inheritance ────────────────── */`,
  `/* Browsers don't inherit font on form controls — fix globally */`,
  `button, input, select, textarea {`,
  `  font-family: inherit;`,
  `}`,
  ``,
  `/* ─── Global focus-visible ──────────────────────────── */`,
  `/* Safety-net focus ring for any element not styled by a component */`,
  `*:focus-visible {`,
  `  outline: var(--border-width-lg) solid var(--color-focus-ring);`,
  `  outline-offset: var(--border-width-lg);`,
  `}`,
  ``,
  `/* ─── Reduced motion ────────────────────────────────── */`,
  `/* Respect OS-level "reduce motion", and <html data-motion="off"> (a site`,
  `   "pause animations" switch — @ds/motion honours the same attribute).`,
  `   .ds-motion-safe opts an element out: it promises to handle both`,
  `   conditions itself with a non-moving animation (Spinner's opacity pulse),`,
  `   which the !important reset would otherwise freeze on its first frame. */`,
  `@media (prefers-reduced-motion: reduce) {`,
  `  :not(.ds-motion-safe), :not(.ds-motion-safe)::before, :not(.ds-motion-safe)::after {`,
  `    animation-duration: 0.01ms !important;`,
  `    animation-delay: 0s !important;`,
  `    animation-iteration-count: 1 !important;`,
  `    transition-duration: 0.01ms !important;`,
  `    transition-delay: 0s !important;`,
  `    scroll-behavior: auto !important;`,
  `  }`,
  `}`,
  `:root[data-motion="off"] :not(.ds-motion-safe),`,
  `:root[data-motion="off"] :not(.ds-motion-safe)::before,`,
  `:root[data-motion="off"] :not(.ds-motion-safe)::after {`,
  `  animation-duration: 0.01ms !important;`,
  `  animation-delay: 0s !important;`,
  `  animation-iteration-count: 1 !important;`,
  `  transition-duration: 0.01ms !important;`,
  `  transition-delay: 0s !important;`,
  `  scroll-behavior: auto !important;`,
  `}`,
);

mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist/tokens.css'), css + adaptive + globals + '\n');
console.log('✓ dist/tokens.css written');

// Motion subset for the JS export (src/index.ts → @ds/motion). Written as
// its own small file so JS consumers bundle ~1KB of timing values instead
// of the whole token tree. Generated — edit tokens.json, not this file.
const motionSubset = {
  $comment: 'Generated by scripts/build-css.mjs from tokens.json — do not edit',
  duration: p.transition.duration,
  easing: p.transition.easing,
  stagger: p.motion.stagger,
  distance: p.motion.distance,
};
writeFileSync(join(root, 'src/motion.json'), JSON.stringify(motionSubset, null, 2) + '\n');
console.log('✓ src/motion.json written');
