/**
 * Generates tokens.css from tokens.json.
 * Outputs:
 *   - dist/tokens.css  (full CSS variable sheet, light + dark)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const tokens = JSON.parse(readFileSync(join(root, 'src/tokens.json'), 'utf8'));

const p = tokens.primitive;

function lines(...parts) {
  return parts.flat().join('\n');
}

/**
 * Resolve a semantic $value. `{primitive.color.stone.500}` references are
 * looked up in tokens.json; anything else (e.g. color-mix() expressions)
 * passes through verbatim. An unresolvable reference FAILS the build —
 * CSS custom properties fail silently at runtime, so catch it here.
 */
function resolveValue(name, raw) {
  const ref = raw.match(/^\{(.+)\}$/);
  if (!ref) return raw;
  const value = ref[1].split('.').reduce((node, key) => node?.[key], tokens);
  if (typeof value !== 'string') {
    throw new Error(`Token "${name}" references "${raw}" which does not exist in tokens.json`);
  }
  return value;
}

function semanticBlock(mode) {
  return Object.entries(tokens.semantic.color[mode]).map(
    ([name, { $value }]) => `  --color-${name}: ${resolveValue(name, $value)};`
  );
}

const css = lines(
  `/* Auto-generated by build-css.mjs — do not edit directly */`,
  `/* Edit packages/tokens/src/tokens.json instead */`,
  ``,
  `/* ─── Primitive tokens ──────────────────────────────── */`,
  `:root {`,
  // colors
  ...Object.entries(p.color).flatMap(([name, shades]) =>
    Object.entries(shades).map(([shade, val]) => `  --color-${name}-${shade}: ${val};`)
  ),
  // spacing — includes fluid steps (--spacing-fluid-*): clamp() between adjacent
  // phi-scale values (16→26, 26→42, 42→68, 68→110px), interpolated linearly
  // across 375px→1200px viewports, same technique as the fluid type scale.
  ...Object.entries(p.spacing).map(([k, v]) => `  --spacing-${k}: ${v};`),
  // aspect ratios — φ-derived (golden = φ:1) plus practical media ratios
  ...Object.entries(p.aspect).map(([k, v]) => `  --aspect-${k}: ${v};`),
  // reading measure — 65ch optimal line length for body text
  ...Object.entries(p.measure).map(([k, v]) => `  --measure-${k}: ${v};`),
  // interaction scale — pressed-state transform shared by all pressable components
  ...Object.entries(p.scale).map(([k, v]) => `  --scale-${k}: ${v};`),
  // safe area — device notch/home-indicator insets, 0px fallback on desktop
  ...Object.entries(p.safeArea).map(([k, v]) => `  --safe-area-${k}: ${v};`),
  // size (control heights, checkbox dimensions — φ/Fibonacci-derived)
  ...Object.entries(p.size).map(([k, v]) => `  --size-${k}: ${v};`),
  // radius
  ...Object.entries(p.radius).map(([k, v]) => `  --radius-${k}: ${v};`),
  // border width
  ...Object.entries(p.borderWidth).map(([k, v]) => `  --border-width-${k}: ${v};`),
  // font family
  ...Object.entries(p.font.family).map(([k, v]) => `  --font-family-${k}: ${v};`),
  // font size
  ...Object.entries(p.font.size).map(([k, v]) => `  --font-size-${k}: ${v};`),
  // font weight
  ...Object.entries(p.font.weight).map(([k, v]) => `  --font-weight-${k}: ${v};`),
  // line height
  ...Object.entries(p.font.lineHeight).map(([k, v]) => `  --line-height-${k}: ${v};`),
  // letter spacing
  ...Object.entries(p.font.letterSpacing).map(([k, v]) => `  --letter-spacing-${k}: ${v};`),
  // shadows
  ...Object.entries(p.shadow).map(([k, v]) => `  --shadow-${k}: ${v};`),
  // transitions
  ...Object.entries(p.transition.duration).map(([k, v]) => `  --transition-duration-${k}: ${v};`),
  ...Object.entries(p.transition.easing).map(([k, v]) => `  --transition-easing-${k}: ${v};`),
  // shorthand transition helpers
  `  --transition-fast:   ${p.transition.duration.fast} ${p.transition.easing.default};`,
  `  --transition-normal: ${p.transition.duration.normal} ${p.transition.easing.default};`,
  `  --transition-slow:   ${p.transition.duration.slow} ${p.transition.easing.default};`,
  // opacity (successive powers of 1/φ ≈ 0.618)
  ...Object.entries(p.opacity).map(([k, v]) => `  --opacity-${k}: ${v};`),
  // z-index
  ...Object.entries(p.zIndex).map(([k, v]) => `  --z-index-${k}: ${v};`),
  // breakpoints (for JS access; use raw values in @media queries)
  ...Object.entries(p.breakpoint).map(([k, v]) => `  --breakpoint-${k}: ${v};`),
  ``,
  `  /* ── Semantic elevation (references, not copies) ─── */`,
  `  /* Emitted as var(--shadow-*) so a shadow-scale change flows through */`,
  ...Object.entries(tokens.semantic.elevation).map(
    ([k, { $value }]) => `  --elevation-${k}: ${$value};`
  ),
  ``,
  `  /* ── Composite tokens (derived from primitives) ──── */`,
  `  --color-overlay: color-mix(in srgb, var(--color-foreground) 38.2%, transparent);`,
  `  --focus-ring-color: color-mix(in srgb, var(--color-focus-ring) 20%, transparent);`,
  `  --focus-ring: 0 0 0 3px var(--focus-ring-color);`,
  `  --focus-ring-inset: inset 0 0 0 3px var(--focus-ring-color);`,
  `  --focus-ring-error: 0 0 0 3px color-mix(in srgb, var(--color-destructive) 20%, transparent);`,
  `}`,
  ``,
  `/* ─── Semantic tokens — light mode ─────────────────── */`,
  `:root, [data-theme="light"] {`,
  semanticBlock('light'),
  `}`,
  ``,
  `/* ─── Semantic tokens — dark mode ──────────────────── */`,
  `.dark, [data-theme="dark"] {`,
  semanticBlock('dark'),
  `}`,
);

const globals = lines(
  ``,
  `/* ─── Scrollbars ────────────────────────────────────── */`,
  `/* Thin, token-colored thumb on an invisible track — recedes`,
  `   into the page instead of announcing itself, and swaps with`,
  `   the theme automatically. Standard properties only: they drive`,
  `   Chromium and Firefox, where the overlay scrollbar stays`,
  `   auto-hiding AND takes the token color. Safari ignores these`,
  `   props and keeps its NATIVE auto-hiding overlay scrollbar`,
  `   (uncolored) — a deliberate choice: styling ::-webkit-scrollbar`,
  `   is the only way to color it in Safari, but doing so forces an`,
  `   always-visible classic bar, which we don't want. Auto-hide`,
  `   wins over color there. See 06-decisions-log.md. */`,
  `* {`,
  `  scrollbar-width: thin;`,
  `  scrollbar-color: var(--color-border-strong) transparent;`,
  `}`,
  ``,
  `/* ─── Scrollbar hiding utility ──────────────────────── */`,
  `.ds-scroll-hidden { scrollbar-width: none; }`,
  `.ds-scroll-hidden::-webkit-scrollbar { display: none; }`,
  ``,
  `/* ─── Form element font inheritance ────────────────── */`,
  `/* Browsers don't inherit font on form controls — fix globally */`,
  `button, input, select, textarea {`,
  `  font-family: inherit;`,
  `}`,
  ``,
  `/* ─── Global focus-visible ──────────────────────────── */`,
  `/* Safety-net focus ring for any element not styled by a component */`,
  `*:focus-visible {`,
  `  outline: 2px solid var(--color-focus-ring);`,
  `  outline-offset: 2px;`,
  `}`,
  ``,
  `/* ─── Reduced motion ────────────────────────────────── */`,
  `/* Respect OS-level "reduce motion" accessibility setting */`,
  `@media (prefers-reduced-motion: reduce) {`,
  `  *, *::before, *::after {`,
  `    animation-duration: 0.01ms !important;`,
  `    animation-iteration-count: 1 !important;`,
  `    transition-duration: 0.01ms !important;`,
  `    scroll-behavior: auto !important;`,
  `  }`,
  `}`,
);

mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist/tokens.css'), css + globals + '\n');
console.log('✓ dist/tokens.css written');
